//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_7Im8QdLfL"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "6iksr9jf3ihk57lh4gmjsjpe1p"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .usEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1scifmao7cjv92poueupkltd8urdvr9nrj1kkp95mplvlbe11pq1"
